id: PA1598FCF
initial_creation_type: input
source_metadata:
  title: Rigdzin Gödem
  language: pt
  description: 'Texts by and about Rigdzin Gödem Ngödrup Gyaltsen (rig ''dzin rgod
    ldem dngos grub rgyal mtshan, 1337–1408), famed discoverer of the so-called Northern
    Treasures (byang gter) revelation:'
  volume:
    c5b0c639263a47969de4dc4e66be5d15:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Aspiration Prayers
    9f72f6ea036e4cf491b9f16172af2deb:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Le'u Dünma
    b906245832c344a2b2c72725d553e7b4:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Le'u Dünma
    8a86827b78f349bdae9337d2bb58ff61:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Le'u Dünma
    9d5c1386dc5b42ca8fa08eb8391eea32:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Le'u Dünma
    6a4aa4e816914c5a8fa5b15295ef6ad7:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Le'u Dünma
    54c353d6d71244ff86ff36fd1c03439c:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Le'u Dünma
    63e6ceaf5c5a42cdbd45655c3cf0c408:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Le'u Dünma
    5a3fe779f02f4c58916e8284d59b4b6e:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Practices
    72555eff3395410baa31dfcb44a9be66:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Sādhanas
created_at: '2022-03-01T01:21:42.535139'
last_modified_at: '2022-03-01T01:21:42.535142'
